### ISSUE TITLE
Error while signing my extension

### ISSUE THREAD

**Issue by vvatelot** [kewisch/action-web-ext#31]
I tried to use your github action like explained in the documentation ([here](https://github.com/marketplace/actions/web-ext-action-for-firefox-add-ons#sign)) but got this error:

```
Run kewisch/action-web-ext@v1
  with:
    cmd: sign
    source: web-ext-artifacts/ecoindex-1.2.zip
    channel: unlisted
    apiKey: ***
    apiSecret: ***
    timeout: 900000
    artifacts: web-ext-artifacts
    verbose: false
    progressBar: false
    ignoreFiles: []
    apiUrlPrefix: https://addons.mozilla.org/api/v4
  env:
    GITHUB_TOKEN: ***
Error: Error: Must specify an add-on id in the manifest at browser_specific_settings.gecko.id
Error: Must specify an add-on id in the manifest at browser_specific_settings.gecko.id
    at WebExtAction.cmd_sign (file:///home/runner/work/_actions/kewisch/action-web-ext/v1/src/action.js:142:15)
    at async main (file:///home/runner/work/_actions/kewisch/action-web-ext/v1/src/index.js:40:16)
```

Not sure where I was wrong... Do you have an idea ?

**Comment by vvatelot** [comment]
Found out how to get the AMO ID!
OK for me!
