### ISSUE TITLE
Could not find file Error

### ISSUE THREAD

**Issue by matthieuEv** [kewisch/action-web-ext#47]
Hey, i was using your action many other times, but recently i encountred this error while running the action on a push tag during the setup jobs. Is there a way to fix this please?

```
Download action repository 'kewisch/action-web-ext@v1' (SHA:d3e19fc24c09986d4ab16fe99322701a1fa2d4a7)

Error: Could not find file '/home/runner/work/_actions/_temp_bd58bd8e-75dd-4e17-87e9-6bdd170b3f74/_staging/kewisch-action-web-ext-d3e19fc/node_modules/dtrace-provider/src/build/node_gyp_bins/python3'.
```

**Comment by kewisch** [comment]
I saw this too recently. I think I might need to update dependencies, or commit the node_modules from a linux machine. What is happening is that that package has binaries, and the tree only has the mac binaries. It cannot find those for the Github runners running ubuntu-latest.

**Comment by matthieuEv** [comment]
Oh okk, thanks for your answer. Let me know when it is fixed 😁

**Comment by kewisch** [comment]
Hopefully this evening, will let you know here!

**Comment by kewisch** [comment]
This is fixed on `main` right now if you want to give it a try, see #51 for details. I will tag `v1` once I've confirmed everything is working.

**Comment by matthieuEv** [comment]
I just tried, and i got this error:

```
Run saphareas/sign-web-extension-action@master
  with:
    sign-listed: true
    amo-api-key: ***
    amo-api-secret: ***
/usr/bin/docker run --name bfb6***********9 --label 48bfb6 --workdir /github/workspace --rm -e "INPUT_WEB-EXT-ID" -e "INPUT_SIGN-LISTED" -e "INPUT_AMO-API-KEY" -e "INPUT_AMO-API-SECRET" -e "WEB_EXT_API_KEY" -e "WEB_EXT_API_SECRET" -e "WEB_EXT_ID" -e "SIGN_LISTED" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/Eseo-tools/Eseo-tools":"/github/workspace" 48bfb6:63c583f5f1124c15834d847c72bd6ade
Signing listed extension...
Building web extension from /github/workspace
Waiting for validation...

WebExtError: Validation failed:
{
  "errors": 1,
  "warnings": 0,
  "notices": 0,
  "success": false,
  "compatibility_summary": {
    "warnings": 0,
    "errors": 0,
    "notices": 0
  },
  "metadata": {
    "listed": true,
    "identified_files": {},
    "id": "{3e********0faf}",
    "manifestVersion": 2,
    "name": "ESEO-Tools",
    "type": 1,
    "version": "1.3.8",
    "firefoxStrictMinVersion": null,
    "experimentApiPaths": {},
    "totalScannedFileSize": 9851,
    "emptyFiles": [],
    "jsLibs": {},
    "unknownMinifiedFiles": []
  },
  "messages": [
    {
      "message": "\"update_url\" is not allowed.",
      "description": "\"applications.gecko.update_url\" or \"browser_specific_settings.gecko.update_url\" are not allowed for Mozilla-hosted add-ons.",
      "file": "manifest.json",
      "uid": "63*******95",
      "type": "error",
      "id": [
        "MANIFEST_UPDATE_URL"
      ],
      "tier": 1
    }
  ],
  "message_tree": {},
  "ending_tier": 5
}
    at file:///usr/local/lib/node_modules/web-ext/lib/cmd/sign.js:101:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Program.execute (file:///usr/local/lib/node_modules/web-ext/lib/program.js:270:7)
    at async file:///usr/local/lib/node_modules/web-ext/bin/web-ext.js:13:1
```

**Comment by kewisch** [comment]
Wrong repo? Looks like you are using saphareas/sign-web-extension-action instead. This error can happen if the channel argument was not provided, and it is trying to submit it to the listed channel (which does not allow update_urls).

**Comment by matthieuEv** [comment]
> Wrong repo? Looks like you are using saphareas/sign-web-extension-action instead. The listed channel does not allow update_urls, so you'll either need to disable sign-listed, or use my action and set channel to unlisted. Or if you wanted to make it listed, remove the update url from your manifest.

Yes my bad. On my side, everything is working 👌
